models/Article.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "articles".
 *
 * @property int $id
 * @property int $author_id
 * @property int $category_id
 * @property string $title
 * @property string $content
 * @property string $created_at
 * @property int $published
 *
 * @property Author $author
 * @property Category $category
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'articles';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                ],
                'value' => new Expression('NOW()'),
            ],     
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['author_id', 'category_id', 'title', 'content', 'published'], 'required'],
            [['author_id', 'category_id', 'published'], 'integer'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 100],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Author::className(), 'targetAttribute' => ['author_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'author_id' => 'Author',
            'category_id' => 'Category',
            'title' => 'Title',
            'content' => 'Content',
            'created_at' => 'Created At',
            'published' => 'Published',
        ];
    }

    /**
     * Gets query for [[Author]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Author::className(), ['id' => 'author_id']);
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}

controllers/ArticleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Article;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Article::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all articles by given author in given category.
     * @return mixed
     */
    public function actionList($authorId = null, $categoryId = null)
    {
        $whereConfig = [];
        $whereConfig['published'] = 1;

        if (!is_null($authorId)) {
            $whereConfig['author_id'] = $authorId;
        }

        if (!is_null($categoryId)) {
            $whereConfig['category_id'] = $categoryId;
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Article::find()
                ->where($whereConfig)
        ]);

        return $this->render('list', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();
        $model->author_id = Yii::$app->user->identity->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        $model->errors;

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/article/_form.php
<?php

use app\helpers\ModelTransformer;
use app\models\Author;
use app\models\Category;
use dosamigos\tinymce\TinyMce;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php
        $categories = Category::getAll();
        $input = ModelTransformer::mapIdsToNames($categories);
        echo $form->field($model, 'category_id')->dropdownList($input);
    ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->widget(TinyMce::className(), [
        'options' => ['rows' => 18],
        'language' => 'en',
        'clientOptions' => [
            'plugins' => [
                "advlist autolink lists link charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
            ],
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        ]
    ]) ?>

    <?= $form->field($model, 'published')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/article/_small.php
<?php

use app\helpers\ArticleHelper;
use app\models\Author;
use app\models\Category;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;

?>

<div class="article-small container-sm p-0">

    <h2 class="mb-1"><?= Html::a(Html::encode($model->title), ['article/view', 'id' => $model->id]) ?></h2>
    <div class="container">
        <div class="row">
            <?= Html::tag('p', Html::encode(date('j. F Y, G:i', strtotime($model->created_at))), ['class' => 'text-muted mr-1 mb-0']) ?>       
        </div>
        <div class="row mb-3">
            <?= Html::a(Html::encode(Author::findOne($model->author_id)->name), ['article/list', 'authorId' => $model->author_id]) ?>   
            <?= Html::a(Html::encode(Category::findOne($model->category_id)->name), ['article/list', 'categoryId' => $model->category_id], ['class' => 'ml-2']) ?>
        </div>
    </div>
    <?= HtmlPurifier::process(ArticleHelper::extractIntroduction($model->content)) ?>
    <div class="container text-right">
        <?= Html::a('Read more...', ['article/view', 'id' => $model->id]) ?>
    </div>
    
</div> 

views/article/create.php
<?php

use yii\helpers\Html;

$this->title = 'Create Article';

?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/article/index.php
<?php

use app\models\Author;
use app\models\Category;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\grid\ActionColumn;
use yii\grid\DataColumn;
use yii\grid\SerialColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->title = 'Articles';

$dataProvider->sort = false;

?>
<div class="article-index">

    <h1 class="mb-3"><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Article', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => SerialColumn::className()],
            [
                'class' => DataColumn::className(),
                'header' => 'Author',
                'value' => function ($model) {
                    return Author::findOne($model->author_id)->name;
                }

            ],
            [
                'class' => DataColumn::className(),
                'header' => 'Category',
                'value' => function ($model) {
                    return Category::findOne($model->category_id)->name;
                }

            ],
            [
                'label' => 'Title',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model->title, 8), ['view', 'id' => $model->id]);
                }
            ],
            [
                'class' => DataColumn::className(),
                'header' => 'Published',
                'contentOptions' => array('style' => 'width: 1%; white-space: nowrap;'),
                'value' => function ($model) {
                    return $model->published === 1 ? 'Yes' : 'No';
                }
            ],
            [
                'class' => ActionColumn::className(),
                'header' => 'Actions',
                'contentOptions' => array('style' => 'width: 1%; white-space: nowrap;'),
                'buttons' => [ 
                    'update' => function ($url, $model) {
                        return Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']);
                    },
                    'delete' => function($url, $model) {
                        return Html::a('Delete', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]);
                    }
                ],
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/article/list.php
<?php

use yii\widgets\ListView;

$this->title = 'articles';

?>
<div class="article-list">
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_small',
    ]) ?>
</div>

views/article/update.php
<?php

use yii\helpers\Html;

$this->title = 'Update Article: ' . $model->title;

?>
<div class="article-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/article/view.php
<?php

use app\models\Author;
use app\models\Category;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;

$this->title = $model->title;

\yii\web\YiiAsset::register($this);
?>
<div class="article-view">

    <h1 class="mb-1"><?= Html::encode($this->title) ?></h1>
    <div class="container">
        <div class="row">
            <?= Html::tag('p', Html::encode(date('j. F Y, G:i', strtotime($model->created_at))), ['class' => 'text-muted mr-1 mb-0']) ?>       
        </div>
        <div class="row mb-4">
            <?= Html::a(Html::encode(Author::findOne($model->author_id)->name), ['article/list', 'authorId' => $model->author_id]) ?>   
            <?= Html::a(Html::encode(Category::findOne($model->category_id)->name), ['article/list', 'categoryId' => $model->category_id], ['class' => 'ml-2']) ?>
        </div>
    </div>

    <div class="article">
        <?= HtmlPurifier::process($model->content) ?>
    </div>
</div>